Remove star-imports
YatingMusic/miditoolkit pull request #19
Opened 2023-02-08 15:00 UTC by akx

The liberal use of star-imports makes `miditoolkit` export quite a lot of names that probably shouldn't be.

```
>>> import miditoolkit as m
>>> dir(m)
['BLACK_KEY_SATUR', 
 'CHROMA_CMAP', 
 'ControlChange', 
 'DEFAULT_BPM', 
 'Instrument', 
 'KeySignature', 
 'Lyric', 
 'Marker', 
 'MidiFile', 
 'NOTE_CMAP', 
 'Note', 
 'OFFSET_OCTAVE', 
 'PITCH_RANGE', 
 'PITCH_TO_NAME', 
 'PR_CMAP', 
 'Pedal', 
 'PitchBend', 
 'SM_CMAP', 
 'TempoChange', 
 'TimeSignature', 
 'WHITE_KEY_SATUR', 
 'XLABEL_FONT_SIZE', 
 'YLABEL_FONT_SIZE', 
 '__builtins__', 
 '__cached__', 
 '__doc__', 
 '__file__', 
 '__loader__', 
 '__name__', 
 '__package__', 
 '__path__', 
 '__spec__', 
 '__version__', 
 'collections', 
 'containers', 
 'csc_matrix', 
 'ct', 
 'deepcopy', 
 'downsample', 
 'example_midi_file', 
 'functools', 
 'matplotlib', 
 'midi', 
 'mido', 
 'normalize', 
 'notes2pianoroll', 
 'np', 
 'os', 
 'parser', 
 'pianoroll', 
 'pianoroll2notes', 
 'pitch_padding', 
 'plot', 
 'plot_background', 
 'plot_chroma', 
 'plot_grid', 
 'plot_heatmap', 
 'plot_note_entries', 
 'plot_xticks', 
 'plot_yticks', 
 'plt', 
 'pylab', 
 're', 
 'tochroma', 
 'utils', 
 'vis', 
 'warnings']
```

This removes all of the star imports (**so this is a semver major change**) in favor of just regular imports from the respective modules.

2023-11-16 21:30 UTC, Natooz requested changes
Hello 👋
Thank you for the suggestion, and sorry for the late reply, the repo has been idle for some time, I'm currently fixing and improving things here.
I agree with you that star import should be removed.
Here however I thing it would still make sens and be convenient to directly access to the `MidiFile` and container (`Note`, ...) classes directly from the main module.

Would you still be interested in applying these last changes, and solve the branch conflicts that appeared as some changes has been made since?
This should hopefully be featured in the next release.

2023-11-16 21:30 UTC, Natooz commented on README.md
> +from miditoolkit.midi.parser import MidiFile
```suggestion
from miditoolkit import MidiFile
```

2023-11-16 21:30 UTC, Natooz commented on miditoolkit/midi/__init__.py
> -from .parser import *
Just import MidiFile

2023-11-16 21:30 UTC, Natooz commented on miditoolkit/midi/__init__.py
> -from .containers import *
We could import here all container classes to directly access if from `miditoolkit.`

2023-11-16 21:30 UTC, Natooz commented on miditoolkit/__init__.py
> -from .midi import *
Adding MidiFile and container classes

2023-11-19 17:35 UTC, akx commented
I'll try to get back to this next week!

2023-11-21 12:37 UTC, akx commented
@Natooz Rebased, added exports for MidiFile and all of the classes from `containers`.

2023-11-21 13:19 UTC, Natooz approved these changes
Wonderful thank you, everything seems good + tests are passing!

2023-11-21 13:19 UTC, merged